### ISSUE TITLE
Implement analysis available in other parts of ActivityWatch

### ISSUE THREAD

**Issue by ErikBjare** [ActivityWatch/aw-research#1]
We currently use `views` to get analysis done, I think it would be better to write task-specific Python code and call the function directly from an API instead instead of having a query language. Writing queries is a mess right now (imo), and the underlying code is prone to bugs when modifying.

Using this library, and exposing select methods in aw-server API we could make analysis a lot easier as you'd just write Python code for the task at hand and expose it on the server.

 - [ ] AFK filtering
 - [ ] Timeline view
 - [ ] (NEW FEATURE) Hierachy building (AFK? -> window? -> browser tab?)
     - Should play nice with [d3-hierarchy](https://github.com/d3/d3-hierarchy), using the hierarchy we could create beautiful sunburst diagrams.

**Comment by johan-bjareholt** [comment]
I do agree that views and queries are pretty bad at the moment, but it is the most flexible way to fetch and transform data. Hardcoding the chain of transforms has a fair share of downsides, so I think we should seriously consider what will be lost and gained from this transition before start implementing it.

Moving all analysis and transformations to a separate repository I am all for however.

**Comment by ErikBjare** [comment]
Alright, so here it goes. Pros and cons of ditching views and replacing with one API endpoint per analysis.

### Pros

 - Would make it easier to write new analysis/views (a lot easier to do in Python).
 - Would make the code easier to maintain (views/queries are a mess code-quality wise)
 - Analysis could be done both server-side and client-side (Python clients could use the aw-analysis package directly)

### Cons

 - Analysis would have to be written in Python and be statically dependent on the `aw-analysis` version and its feature set (if client want to do some custom analysis not available via the server, they'd have to do it client side)

Really, at this point I don't want anything to do with the views/queries API due to its messy nature. This repo was created out of hope for a better way.

If you have any more, please write a comment with them.

**Comment by johan-bjareholt** [comment]
> Would make it easier to write new analysis/views (a lot easier to do in Python).

Not easier, analysis/views implementation is already written in python. The only difference would be that the removal of the json queries would make it cleaner to call everything within python, but since it's all just a chain of transforms it would not call it "easier" just "cleaner".

> Would make the code easier to maintain (views/queries are a mess code-quality wise)

Yep

> Analysis could be done both server-side and client-side (Python clients could use the aw-analysis package directly)

All transforms are already in aw-core, so this is already possible.


Seems like you are mixing a few things up? The only thing that would change from this would be that we no longer would need the json queries, we would still need some kind of "view" so we can cache and summarize over larger periods of time and not just daily.

**Comment by ErikBjare** [comment]
Ah yes, sorry for being unclear.

I guess the first step would be to implement the currently used views as normal functions. Caching and such could come later (I have a few ideas on how to solve that).

**Comment by ErikBjare** [comment]
This is easily done but doesn't really need to be done anymore since `query2` is in the works. Closing.
